on: [push]

name: commit

jobs:
  check:
    name: check
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: "cargo install wasm-pack"
    - run: "npm ci && npm run build"
    - run: "git status --porcelain"
    - run: "[[ -z $? ]]"