on: [push]

name: commit

jobs:
  check:
    name: check
    runs-on: ubuntu-22.04
    steps:
    - run: "cargo install wasm-pack"
    - run: "npm ci && npm run build"
    - run: "git status --porcelain"
    - run: "[[ -z $? ]]"